server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smbms?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  devtools:
    restart:
      exclude: static/*,public/*,templates/*
  jackson:
    date-format: yyyy-MM-dd
  mvc:
    date-format: yyyy-MM-dd
mybatis:
  type-aliases-package: com.it.user.user

  configuration:
    lazy-loading-enabled: false