spring:
  #配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/activity?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  #禁止缓存
  thymeleaf:
    cache: false
mybatis:
  #pojo包别名
  type-aliases-package: com.it.activiti.activiti.pojo
  configuration:
    #懒加载
    lazy-loading-enabled: false
  # activiti配置
  activiti:
    # true  代表没有表就自动创建
    database-schema-update: true
    # 记录级别,默认audit
    history-level: full
    # （可选）自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false
    # （可选）默认流程定义文件存放目录
    process-definition-location-prefix: classpath:/processes/
logging:
    #日志
  config: classpath:log/logback-spring.xml
  path: /LogBack
